baseURL: "https://333rosky.github.io/"
title: "Romain Bastiani"
languageCode: "fr-fr"
theme: "PaperMod"

# Génération dans docs/ pour GitHub Pages (paramétrable côté Pages)
publishDir: "docs"

pagination:
  pagerSize: 10
enableRobotsTXT: true
canonifyURLs: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  title: "Romain Bastiani"
  description: "Portfolio de Quantitative Researcher — disponible à partir d'avril 2026"
  keywords: ["Portfolio", "Blog", "Hugo", "PaperMod"]
  author: "Romain Bastiani"
  DateFormat: "2006-01-02"
  defaultTheme: auto
  disableThemeToggle: false
  ShowBreadCrumbs: true
  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  comments: false

  profileMode:
    enabled: true
    title: "Romain Bastiani"
    subtitle: "Quantitative Researcher — à la recherche d'un poste de Quantitative Analyst (avril 2026)"
    imageUrl: "/Linkedin PP.jpg"
    imageTitle: "Photo de profil"
    buttons:
      - name: "Projets"
        url: "/projects/"
      - name: "CV"
        url: "/cv.pdf"

  socialIcons:
    - name: github
      url: "https://github.com/333Rosky"
    - name: linkedin
      url: "https://www.linkedin.com/in/romain-bastiani-118072173/"

menu:
  main:
    - name: "Accueil"
      url: "/"
      weight: 1
    - name: "Expériences"
      url: "/experience/"
      weight: 2
    - name: "Éducation"
      url: "/education/"
      weight: 3
    - name: "Projets"
      url: "/projects/"
      weight: 4

permalinks:
  posts: "/posts/:slug/"

markup:
  goldmark:
    renderer:
      unsafe: true

privacy:
  youtube:
    privacyEnhanced: true
  x:
    enableDNT: true

