baseURL: "https://333rosky.github.io/"
title: "Romain Bastiani"
languageCode: "fr-fr"
theme: "PaperMod"

# Génération dans docs/ pour GitHub Pages (paramétrable côté Pages)
publishDir: "docs"
defaultContentLanguage: "fr"

pagination:
  pagerSize: 10
enableRobotsTXT: true
canonifyURLs: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  title: "Romain Bastiani"
  description: "Quantitative Researcher spécialisé en modèles factoriels, trend‑following et marchés de matières premières. Python/ML, data tooling et stratégies systématiques."
  keywords: ["Portfolio", "Blog", "Hugo", "PaperMod"]
  author: "Romain Bastiani"
  DateFormat: "2006-01-02"
  defaultTheme: auto
  disableThemeToggle: false
  ShowBreadCrumbs: true
  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  comments: false

  profileMode:
    enabled: true
    title: "Romain Bastiani"
    subtitle: "Quantitative Researcher spécialisé en modèles factoriels, trend‑following et marchés de matières premières. Je conçois des pipelines de recherche, des outils data et des stratégies systématiques en Python (pandas, NumPy, scikit‑learn), à l’interface entre recherche quantitative et engineering. Intérêts: flux CTA, microstructure de marché, gestion des risques."
    imageUrl: "/Linkedin PP.jpg"
    imageTitle: "Photo de profil"
    buttons:
      - name: "Projets"
        url: "/projects/"
      - name: "CV"
        url: "/cv.pdf"

  socialIcons:
    - name: github
      url: "https://github.com/333Rosky"
    - name: linkedin
      url: "https://www.linkedin.com/in/romain-bastiani-118072173/"

menu:
  main:
    - name: "Accueil"
      url: "/"
      weight: 1
    - name: "Expériences"
      url: "/experience/"
      weight: 2
    - name: "Éducation"
      url: "/education/"
      weight: 3
    - name: "Projets"
      url: "/projects/"
      weight: 4

permalinks:
  posts: "/posts/:slug/"

markup:
  goldmark:
    renderer:
      unsafe: true

privacy:
  youtube:
    privacyEnhanced: true
  x:
    enableDNT: true

languages:
  fr:
    languageName: "Français"
    weight: 1
  en:
    languageName: "English"
    weight: 2
    params:
      profileMode:
        enabled: true
        title: "Romain Bastiani"
        subtitle: "Quantitative Researcher focused on factor models, trend‑following, and commodity markets. I build research pipelines, data tooling, and systematic strategies in Python (pandas, NumPy, scikit‑learn), bridging quantitative research and engineering. Interests: CTA flows, market microstructure, risk management."
    menu:
      main:
        - name: "Home"
          url: "/en/"
          weight: 1
        - name: "Experience"
          url: "/en/experience/"
          weight: 2
        - name: "Education"
          url: "/en/education/"
          weight: 3
        - name: "Projects"
          url: "/en/projects/"
          weight: 4

